In [11]:
### Numpy
import numpy as np

## convert a list to np array
arr1 = np.array([1, 2, 3, 4, 5]) # 1D array
# print(arr1)
# print(type(arr1))

l2 = [[1,2,3],[4,5,6]]
arr2 = np.array(l2) # 2D array

l3 = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
arr3 = np.array(l3)
## shape
# print(np.shape(arr3))

## dimention
print(arr2.ndim)




2


In [16]:
## Indexing , access 1D array

arr1 = np.array([1,  2,  3,  4,  5])
#                0   1   2   3   4
#               -5  -4  -3  -2   -1
print(arr1[0])
print(arr1[-1])
print(arr1[0]+arr1[-1])

1
5
6


In [20]:
## Index 2D 
# arr2 = np.array([[1,2,3],[4,5,6]])

# arr2[1,1]
# print(arr2)

## Index 3D
l3 = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
arr3 = np.array(l3)
print(arr3[0,1,2])

[[1 2 3]
 [4 5 6]]
6


In [28]:
## Slicing in 1D array

arr = np.array([1,2,3,4,5,6,7])

# arr[start:end:step]
# print(arr[1:5])
# print(arr[:4])
# print(arr[4:])
# print(arr[1:5:2])
# print(arr[::2])

arr2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2d[1,1:4])


[7 8 9]


In [31]:
#shape and size
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr.size) # print(arr.shape[0]*arr.shape[1])
print(arr.shape[0]*arr.shape[1])


(2, 4)
8
8


In [41]:
## convert 1d to 2d array
##reshape

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12]) #1D
# arr.shape
newarr = arr.reshape(6,2) #2D
print(newarr)

newarr2 = arr.reshape(2,2,3)
print(newarr2)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [44]:
## is reshape view or copy? view
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12]) #1D
n1 = arr.reshape(3,4)
n2 = arr.copy().reshape(3,4)
print(n1.base)
arr[0] = 0 
print(arr)
print(n1)
print(n2)




[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  2  3  4  5  6  7  8  9 10 11 12]
[[ 0  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [51]:
## reshape with -1 dim

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])

newarr = arr.reshape(2,2,-1)
# arr.size
newarr.shape
newarr2 = newarr.reshape(-1)
newarr2.shape

(16,)

In [53]:
# iterating in numpy array
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr.shape
for x in arr:
    for y in x:
        for z in y:
            print(z)




1
2
3
4
5
6
7
8
9
10
11
12


In [67]:
# concat
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[5,6],
                 [7,8]])

arr1.shape
arr_row = np.concatenate((arr1, arr2) , axis =0 ) #concat along with axis =0
arr_col = np.concatenate((arr1, arr2) , axis =1 )
print(arr_row)
print(arr_row.shape)
print(arr_col)
print(arr_col.shape)

arr1 = np.array([[1,2,3],
                [4,5,6]])   #(2,3)
arr2 = np.array([[7,8],
                [9,10]])    #(2,2)
new_arr = np.concatenate((arr1,arr2), axis =1 )
new_arr.shape

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


(2, 5)

In [74]:
## 1D array concat
from numpy import array as ar

arr1 = ar([1,2,3,4,5])
arr2 = ar([6,7,8,9,10])

narr = np.concatenate((arr1,arr2), axis = 0)
print(narr)


arr1 = ar([[1,2,3,4,5]])
arr2 = ar([[6,7,8,9,10]])

narr = np.concatenate((arr1,arr2), axis = 0)
print(narr)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
## Stack 
#hstack
#vstack
#dstack
## HW : difference stack vs concat
# aya be stack ham niaaz darim ya kheir

In [83]:
## split
arr = ar([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
print(arr.shape)
print(arr)
new_arr = np.array_split(arr,3,axis=0)
new_arr1 = np.vsplit(arr,3)
print(len(new_arr))
print(new_arr[2].shape)

(6, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
3
(2, 3)


In [93]:
## search an array
# arr  = ar([1,2,3,4,5,4,4])

# x = np.where(arr == 4)

# print(x[0])

arr = ar([1,6,5,6,8,11,9])
x = np.searchsorted(np.sort(arr),7)
print(x)
print(np.sort(arr))


4
[ 1  5  6  6  8  9 11]


In [94]:
## sort in 2D array
arr = ar([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [95]:
## Array Filtering
arr = ar([44,42,43,44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[ True False  True  True]
[44 43 44]


In [113]:
### ones and zeros
a1 = np.ones((3,4))*4
print(a1)
# a2 = np.ones((1,3))
# print(a2.T)
# a3 = np.zeros((3,3))
# print(a3)
print(np.square(a1))
print(np.sqrt(a1))
print(np.sum(a1,axis=0))

[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[12. 12. 12. 12.]
